#! /usr/bin/env bash
set -e
SERVICE_ROOT=${TOKEN_SERVICE_ROOT?You must specify a TOKEN_SERVICE_ROOT}
TOKEN=$(curl -s ${SERVICE_ROOT}/create?expiration_seconds=10000 --data '{"data":"some data"}' | jq --raw-output ".token")
TOKEN2=$(curl -s ${SERVICE_ROOT}/create?expiration_seconds=10000 --data '{"data":"some data"}' | jq --raw-output ".token")
if [ "${TOKEN}" == "${TOKEN2}" ]; then
  echo "IT'S BROKEN THOSE TOKENS SHOULD BE DIFFERENT"
else
  echo "All good"
fi

