#! /usr/bin/env bash
set -e
SERVICE_ROOT=${TOKEN_SERVICE_ROOT?You must specify a TOKEN_SERVICE_ROOT}
TOKEN=$(curl -s ${SERVICE_ROOT}/create?expiration_seconds=10000 --data "data=data" --data "mynum=4"  | jq --raw-output ".token")
curl -s ${SERVICE_ROOT}/validate/${TOKEN}

